services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./admin/.env
    restart: always

  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - ./chatbot/.env
    restart: always
